### ISSUE TITLE
`TypeId` equality may not necessarily imply type equality

### ISSUE THREAD

**Issue by 8573** [GoldsteinE/cismute#2]
https://github.com/GoldsteinE/cismute/blob/c4dbb123592b582fc2f503a6ebca87f8349583bb/src/lib.rs#L192-L194

I looked into how this crate works and I see that it appears to rely on `TypeId`s to be "globally unique" as their documentation claims.

I apologize if I bear bad news, but that documentation may be wrong, and relying on equality of `TypeId`s to imply equality of types may be unsound. This issue has been open for more than eight years, since before Rust 1.0:
* https://github.com/rust-lang/rust/issues/10389

**Comment by GoldsteinE** [comment]
Relying on equality of `TypeId` is technically unsound, but many libraries in the ecosystem (including the standard library with `Any::downcast_ref`!) rely on it. `TypeMap`s are used extensively in Rust and have the same problem. Furthermore, accidentally causing a collision is really hard.

In other words, if this crate is unsound, then the standard library, hyper, actix-web and many other crates are unsound.
